[versions]
kotlin = "1.9.23"
kotlinxSerialization = "1.6.3"
kotlinxCoroutines = "1.8.0"
kotlinxKsp = "1.9.23-1.0.20"
androidGradlePlugin = "8.3.2"
androidxComposeBom = "2024.04.00"
androidxCompose = "1.5.0"
androidxComposeCompiler = "1.5.11"
androidxMaterial3 = "1.1.1"
androidxCore = "1.12.0"
androidxAppcompat = "1.6.1"
androidxWindow = "1.2.0"
androidxWork = "2.9.0"
androidxNavigation = "2.7.7"
androidxLifecycle = "2.7.0"
androidxActivityCompose = "1.8.2"
androidxHiltWork = "1.2.0"
androidxHiltNavigationCompose = "1.2.0"
androidxRoom = "2.6.1"
androidxSplashScreen = "1.0.1"
androidxDatastorePreferences = "1.0.0"
androidxTestCore = "1.5.0"
androidxTestJunit = "1.1.5"
androidxEspresso = "3.5.1"
androidxMacroBenchmark = "1.2.4"
androidxTestuiautomator = "2.3.0"
material = "1.11.0"
accompanist = "0.34.0"
hiltAndroid = "2.51.1"
timberLogger = "5.0.1"
retrofit = "2.11.0"
moshi = "1.15.1"
coil = "2.6.0"
ktor = "2.3.10"
gradleSecret = "2.0.1"
junit = "4.13.2"
appcompat = "1.6.1"
arrow = "1.2.4"
detekt = "1.23.6"
kotlinter = "4.3.0"



[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-ui-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-Window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version = "2.9.0" }
androidx-NavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-LifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-LifecycleViewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-LifecycleLiveDataKtx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-LifecycleComposeRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-LifecycleViewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-ActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-Datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-HiltWork = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }
androidx-HiltKaptCompiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHiltWork" }
androidx-roomCommon = { group = "androidx.room", name = "room-common", version.ref = "androidxRoom" }
androidx-roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-test-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestuiautomator" }
kotlix-Serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlix-CoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlix-CoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlix-CoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
accompanist-FlowLayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }
timberLogger = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberLogger" }
hilt_NavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
hilt_Android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt_KaptCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltAndroid" }
hilt_androidTesting = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltAndroid" }
retrofitMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
coilCompose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-kotlinxSerilization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-gsonSerilization = { group = "io.ktor", name = "ktor-serialization-gson", version.ref = "ktor" }
ktor-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-androidClient = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-LoggingClient = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-ciaoClient = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-okhttpClient = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
arrow_optics = { module = "io.arrow-kt:arrow-optics" }
arrow_optics_ksp = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }

#build-logic dependecies
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[bundles]
compose = [
    "compose-animation",
    "compose-foundation",
    "compose-ui",
    "compose-ui-toolingPreview",
    "compose-ui-tooling",
    "compose-runtime",
    "compose-material",
    "compose-material-iconsExtended"]
ktor = [
    "ktor-core",
    "ktor-kotlinxSerilization",
    "ktor-gsonSerilization",
    "ktor-contentNegotiation",
    "ktor-androidClient",
    "ktor-LoggingClient",
    "ktor-ciaoClient",
    "ktor-okhttpClient"
]
[plugins]
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "gradleSecret" }
andoirdGradle = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinGradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinx-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinxKsp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

#custom plugins
weather-android-application = { id = "weather.android.application", version = "unspecified" }
weather-android-library = { id = "weather.android.library", version = "unspecified" }
weather-android-compose-application = { id = "weather.compose.application", version = "unspecified" }
weather-android-compose-library = { id = "weather.compose.library", version = "unspecified" }
