
naming:
  FunctionNaming:
    active: true
    #    functionPattern: '[a-zA-Z][a-zA-Z]*'
    ignoreAnnotated:
      - 'Composable'
complexity:
  LongMethod:
    active: true
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    active: true
    ignoreAnnotated:
      - 'Composable'